In [3]:
import numpy as np

In [4]:
array1 = np.array([21, 19])
array2 = np.array([1, 7])
print("Original numbers:")
print(array1)
print(array2)
print("Comparison - greater : ", np.greater(array1, array2))
print("Comparison - greater_equal : ", np.greater_equal(array1,array2))
print("Comparison - less : ", np.less(array1, array2))
print("Comparison - less_equal : ", np.less_equal(array1, array2))

Original numbers:
[21 19]
[1 7]
Comparison - greater :  [ True  True]
Comparison - greater_equal :  [ True  True]
Comparison - less :  [False False]
Comparison - less_equal :  [False False]


# Question 2

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)



array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

# Question 3:

In [8]:
array = np.array([[21,19],[1,7]])
print("Original array:")
print(array)
print("\nSum of all the elements:", np.sum(array))
print("\nSum of each column:", np.sum(array, axis=0))
print("\nSum of each row:", np.sum(array, axis=1))

Original array:
[[21 19]
 [ 1  7]]

Sum of all the elements: 48

Sum of each column: [22 26]

Sum of each row: [40  8]


# Question 4:

In [9]:
x = np.array([21,19])
y = np.array([1,7])


In [10]:
np.divide(x,y)

array([21.        ,  2.71428571])

In [11]:
np.multiply(x,y)

array([ 21, 133])

In [12]:
np.add(x,y)

array([22, 26])

In [13]:
np.subtract(x,y)

array([20, 12])

# Question 5:

In [15]:
array = np.array([0,30,45,60,90]) 
print("sin: array of angles given in degrees")
print(array * np.pi / 180.)
print("\ncos: array of angles given in degrees")
print(array * np.pi / 180.)
print("\ntangent: array of angles given in degrees")
print(array * np.pi / 180.)

sin: array of angles given in degrees
[0.         0.52359878 0.78539816 1.04719755 1.57079633]

cos: array of angles given in degrees
[0.         0.52359878 0.78539816 1.04719755 1.57079633]

tangent: array of angles given in degrees
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


# Question 6:

In [17]:
import pandas as pd

In [20]:
data = {'Name' : ['Raji','pree','Akhash','keerth','swetha','gayu','bala'],'Age' : [25,27,25,25,23,27,25],
        'Course' : ['AIML & Python','AIML','AIML','AIML','AIML','AIML','AIML'],
        'Qualified' : ['Yes','Yes','Yes','Yes','Yes','No','No']}


labels = ['a','b','c','d','e','f','g']

In [21]:
df = pd.DataFrame(data, labels)
df

Name  Age         Course Qualified
a    Raji   25  AIML & Python       Yes
b    pree   27           AIML       Yes
c  Akhash   25           AIML       Yes
d  keerth   25           AIML       Yes
e  swetha   23           AIML       Yes
f    gayu   27           AIML        No
g    bala   25           AIML        No

# Question 7:

In [22]:
print('Select Specific Columns')
df[['Name','Course']]

Select Specific Columns


Name         Course
a    Raji  AIML & Python
b    pree           AIML
c  Akhash           AIML
d  keerth           AIML
e  swetha           AIML
f    gayu           AIML
g    bala           AIML

# Question 8:

In [24]:
data_frame1 = {'Employee_id' : ['emp001','emp002','emp003','emp004'],
                            'Employee_name' : ['Raji','Akhash','Charan','Keerth'],
                            'Designation': ['Data-Analyst', 'Data-Analyst', 'ML-Eng', 'Software Developer']}
index1 = ['a','b','c','d']
d1 = pd.DataFrame(data_frame1, index1)
d1

Employee_id Employee_name         Designation
a      emp001          Raji        Data-Analyst
b      emp002        Akhash        Data-Analyst
c      emp003        Charan              ML-Eng
d      emp004        Keerth  Software Developer

# Question 9:

In [25]:
data_frame2 = {'Employee_id' : ['emp005','emp006','emp007','emp008'],
                            'Employee_name' : ['Akhash','laksh','aarthy','Siva'],
                            'Designation': ['Software Engineer','Softawre Developer','Software Engineer','Web-Developer']}
index2 = ['e','f','g','h']
d2 = pd.DataFrame(data_frame2, index2)
d2

Employee_id Employee_name         Designation
e      emp005        Akhash   Software Engineer
f      emp006         laksh  Softawre Developer
g      emp007        aarthy   Software Engineer
h      emp008          Siva       Web-Developer

In [26]:
print('Joining the Two Data Frames along with the Rows: ')
result_data_frame = pd.concat([d1, d2])
result_data_frame

Joining the Two Data Frames along with the Rows: 


Employee_id Employee_name         Designation
a      emp001          Raji        Data-Analyst
b      emp002        Akhash        Data-Analyst
c      emp003        Charan              ML-Eng
d      emp004        Keerth  Software Developer
e      emp005        Akhash   Software Engineer
f      emp006         laksh  Softawre Developer
g      emp007        aarthy   Software Engineer
h      emp008          Siva       Web-Developer

# Question 9:

In [28]:
import numpy as np
data = {'Name' : ['Hari', 'Akhil', 'Swetha', 'Preetha'],
        'Age' : [25,24,np.nan,np.nan]}
index = ['a','b','c','d']
df1 = pd.DataFrame(data , index)
df1

Name   Age
a     Hari  25.0
b    Akhil  24.0
c   Swetha   NaN
d  Preetha   NaN

In [29]:
df1.dropna()

Name   Age
a   Hari  25.0
b  Akhil  24.0

In [30]:
df1['Age'].isnull()

a    False
b    False
c     True
d     True
Name: Age, dtype: bool

# Question 10:

In [31]:

array_data = pd.Series([1,2,3,4,5,6,7,8,9,21.01,19.07], index = ['a','b','c','d','e','f','g','h','i','j','k'])

In [32]:
array_data

a     1.00
b     2.00
c     3.00
d     4.00
e     5.00
f     6.00
g     7.00
h     8.00
i     9.00
j    21.01
k    19.07
dtype: float64